repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: name-tests-test
        exclude: "_example.py"
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
        exclude: "tests"
        args: ['--ignore=E501']
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v2.1.0
  #   hooks:
  #     - id: add-trailing-comma
  #       args: [--py36-plus]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
      - id: autopep8
        exclude: "tests"
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
  - repo: local
    hooks:
      - id: pytest-unit-check
        name: pytest-unit-check
        entry: python -m pytest tests/unit -n 10 # (you need to run pre-commit inside a poetry shell)
        language: system
        require_serial: false
        pass_filenames: false
        always_run: true

  # - repo: local
  #   hooks:
  #     - id: argo-lint
  #       name: argo-lint
  #       entry: argo lint cron_node_health_check.yaml
  #       language: system
  #       pass_filenames: true
  #       always_run: true
